language: node_js

node_js: "lts/*"

os: linux

cache:
  yarn: true

before_install:
  - npm i -g yarn

script:
  - yarn lint
  - yarn nyc

after_success:
  - chmod 0755 /home/travis/build/l3laze/node-dot-property/.nyc_output
  - yarn textcov
  - yarn codecov && yarn codacy

notifications:
  email: false
